services:
  db:
    image: postgres:latest
    container_name: postgres-container
    environment:
      POSTGRES_USER: shamim
      POSTGRES_PASSWORD: shamim
    volumes:
      - odoo_db_data:/var/lib/postgresql/data

  odoo:
    build:
      context: .
      dockerfile: odoo.dockerfile
    container_name: odoo-enterprise
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      # - Mounting custom addons
      - /opt/odoo/custom-addons/odoo-18-ce:/mnt/extra-addons
      # - Mounting enterprise addons
      - /opt/odoo/server/odoo_18.0+e/odoo/addons:/mnt/odoo-18-ee
      # - replacing default conf file with custom conf file
      - ./conf:/etc/odoo
    command: >
      odoo -d mydatabase -i base,P1705_VendorBid,admin_reset

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin4
    depends_on:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - ./pgadmin/servers.json:/pgadmin4/servers.json
      - ./pgadmin/pgpass:/pgpass
    restart: always
  caddy:
    image: caddy:latest
    container_name: caddy-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - odoo
      - pgadmin
    restart: always

volumes:
  odoo_db_data:
  pgadmin_data:
  caddy_data:
  caddy_config:
