services:
  db:
    image: postgres:latest
    container_name: postgres-container
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: shamim
      POSTGRES_PASSWORD: shamim
    volumes:
      - odoo_db_data:/var/lib/postgresql/data

  odoo:
    build:
      context: .
      dockerfile: odoo.dockerfile
    container_name: odoo-enterprise
    depends_on:
      - db
    environment:
      - HOST=db
      - USER=shamim
      - PASSWORD=shamim
      - ODOO_DB_NAME=mydatabase
    ports:
      - "8069:8069"
    volumes:
      - /opt/odoo/custom-addons/odoo-18-ce:/mnt/extra-addons
      - /opt/odoo/server/odoo-18-ee/odoo/addons:/mnt/odoo-18-ee
      - ./conf:/etc/odoo
    command: >
      odoo --config=/etc/odoo/odoo.conf -d mydatabase -i base,P1705_VendorBid,admin_reset

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin4
    depends_on:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - ./pgadmin/servers.json:/pgadmin4/servers.json
      - ./pgadmin/pgpass:/pgpass
    restart: always
  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/certs:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - odoo
      - pgadmin
    restart: always

volumes:
  odoo_db_data:
  pgadmin_data:
