services:
  db:
    image: postgres:latest
    container_name: postgres-container
    environment:
      POSTGRES_USER: shamim
      POSTGRES_PASSWORD: shamim
    volumes:
      - odoo_db_data:/var/lib/postgresql/data
    networks:
      - odoo-net

  # Container name must same as service name and conf file name
  odoo-admin-18ee:
    build:
      context: ./dockerfile
      dockerfile: odoo-admin-18ee.dockerfile
    container_name: odoo-admin-18ee
    depends_on:
      - db
    environment:
      - HOST=db
      - USER=shamim
      - PASSWORD=shamim
    volumes:
      - /opt/odoo/custom-addons/odoo-18ee-custom-addons:/mnt/extra-addons
      - /opt/odoo/server/odoo_18.0+e/odoo/addons:/mnt/odoo-18-ee
      - ./conf/bjit.conf:/etc/odoo/odoo.conf
    command: >
      odoo -d bjit-odoo-db -i base,admin_reset,website
    networks:
      - odoo-net


  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin4
    depends_on:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - ./pgadmin/servers.json:/pgadmin4/servers.json
      - ./pgadmin/pgpass:/pgpass
    restart: always
    networks:
      - odoo-net

  caddy:
    image: caddy:latest
    container_name: caddy-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - odoo-admin-18ee
      - pgadmin
    restart: always
    networks:
      - odoo-net

networks:
  odoo-net:
    name: odoo-net
    driver: bridge

volumes:
  odoo_db_data:
  pgadmin_data:
  caddy_data:
  caddy_config:
